Repository fossasia/pslab-firmware, pull requests merged in 2021-06, with the labels that each got.

#91 chore: upload hex artifacts upon CI
  .github/workflows/main-builder.yml
Labels: chore

#90 docs: added repository structure to readme
  README.md
Labels: documentation

#93 feat: update host application run script
  bootloader-host-application/run-host.sh
Labels: chore

#95 feat: dual sine waves
  pslab-core.X/commands.c
  pslab-core.X/instruments/wavegenerator.c
  pslab-core.X/instruments/wavegenerator.h
Labels: feature

#96 feat: map reference oscillator
  pslab-core.X/commands.c
  pslab-core.X/instruments/wavegenerator.c
  pslab-core.X/instruments/wavegenerator.h
Labels: feature

#97 feat: set and get pin states
  pslab-core.X/commands.c
  pslab-core.X/registers/system/pin_manager.c
  pslab-core.X/registers/system/pin_manager.h
Labels: feature

#98 refactor: comparator voltage file
  pslab-core.X/mcc_generated_files/cvr.c
  pslab-core.X/mcc_generated_files/cvr.h
  pslab-core.X/nbproject/configurations.xml
  pslab-core.X/registers/comparators/cvr.c
  pslab-core.X/registers/comparators/cvr.h
  pslab-core.X/registers/system/system.c
Labels: enhancement

#103 feat: pin initialisation and mapping
  pslab-core.X/bus/uart/uart1.c
  pslab-core.X/registers/system/interrupt_manager.c
  pslab-core.X/registers/system/pin_manager.c
  pslab-core.X/registers/system/pin_manager.h
Labels: feature

#101 feat: oscilloscope capture one channel
  pslab-core.X/commands.c
  pslab-core.X/helpers/buffer.c
  pslab-core.X/helpers/buffer.h
  pslab-core.X/helpers/light.h
  pslab-core.X/instruments/oscilloscope.c
  pslab-core.X/instruments/oscilloscope.h
  pslab-core.X/nbproject/configurations.xml
  pslab-core.X/registers/converters/adc1.c
Labels: feature
